// Code generated by goctl. DO NOT EDIT.
// Source: order.proto

package server

import (
	"context"

	"myFlashSale/order/rpc/internal/logic"
	"myFlashSale/order/rpc/internal/svc"
	"myFlashSale/order/rpc/pb/pb"
)

type OrderServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedOrderServiceServer
}

func NewOrderServiceServer(svcCtx *svc.ServiceContext) *OrderServiceServer {
	return &OrderServiceServer{
		svcCtx: svcCtx,
	}
}

// 创建订单
func (s *OrderServiceServer) CreateOrder(ctx context.Context, in *pb.CreateOrderRequest) (*pb.CreateOrderResponse, error) {
	l := logic.NewCreateOrderLogic(ctx, s.svcCtx)
	return l.CreateOrder(in)
}
