// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"myFlashSale/payment/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/payment/createpayment",
				Handler: CreatePaymentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/payment/pay",
				Handler: PayHandler(serverCtx),
			},
		},
	)
}
