// Code generated by goctl. DO NOT EDIT.
// Source: payment.proto

package server

import (
	"context"

	"myFlashSale/payment/rpc/internal/logic"
	"myFlashSale/payment/rpc/internal/svc"
	"myFlashSale/payment/rpc/pb/pb"
)

type PaymentServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedPaymentServiceServer
}

func NewPaymentServiceServer(svcCtx *svc.ServiceContext) *PaymentServiceServer {
	return &PaymentServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *PaymentServiceServer) CreatePayment(ctx context.Context, in *pb.CreatePaymentRequest) (*pb.CreatePaymentResponse, error) {
	l := logic.NewCreatePaymentLogic(ctx, s.svcCtx)
	return l.CreatePayment(in)
}

func (s *PaymentServiceServer) Pay(ctx context.Context, in *pb.PayReq) (*pb.PayResp, error) {
	l := logic.NewPayLogic(ctx, s.svcCtx)
	return l.Pay(in)
}
