// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package server

import (
	"context"

	"myFlashSale/user/rpc/internal/logic"
	"myFlashSale/user/rpc/internal/svc"
	"myFlashSale/user/rpc/pb/pb"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Login(ctx context.Context, in *pb.UserRequest) (*pb.UserResponse, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) Register(ctx context.Context, in *pb.UserRequest) (*pb.UserResponse, error) {
	l := logic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) Checkdeposit(ctx context.Context, in *pb.CheckDepositReq) (*pb.CheckDepositResp, error) {
	l := logic.NewCheckdepositLogic(ctx, s.svcCtx)
	return l.Checkdeposit(in)
}

func (s *UserServer) Updatadeposit(ctx context.Context, in *pb.UpdataDepositReq) (*pb.UpdataDepositResp, error) {
	l := logic.NewUpdatadepositLogic(ctx, s.svcCtx)
	return l.Updatadeposit(in)
}
